version: '3.2'
services:
  db:
    image: mongo:4.0.5
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: klendathu-admin
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: klendathu
    ports:
      - 27017:27017
    volumes:
      - $PWD/data:/data/db
  db-admin:
    image: mongo-express:0.49.0
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: klendathu-admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_MONGODB_PORT: 27017
    depends_on:
      - db
  imaginary:
    image: h2non/imaginary:latest
    container_name: imgproc
    environment:
       PORT: 9000
    command: -enable-url-source
    ports:
      - "9000:9000"
  redis:
    image: redis:5.0-alpine
    container_name: redis
    ports:
      - "6379:6379"
