version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15
    environment:
      NODE_ENV: development
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: npm run build-client
  test:
    docker:
      - image: circleci/node:10.15
      - image: circleci/mongo:4.0.5
        environment:
          MONGO_INITDB_ROOT_USERNAME: klendathu-admin
          MONGO_INITDB_ROOT_PASSWORD: example
          MONGO_INITDB_DATABASE: klendathu-circleci
    environment:
      NODE_ENV: development
      DB_HOST: "mongodb://localhost:27017"
      DB_NAME: klendathu-circleci
      DB_USER: klendathu-admin
      DB_PASSWORD: example
      LOG_LEVEL: debug
      CLIENT_PROXY: 'false'
      JWT_SECRET: not-so-secret
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: npm run lint-server
      - run: npm run lint-client
      - run: npm run test-server
      - run: npm run test-client

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
